version: "3"

services:
  web:
    build:
      context: .
    image: api_party
    container_name: api_party
    command: yarn dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
